const assets={'/': [__INDEX_HTML__,'text/html; charset=utf-8'], '/styles.css':[__STYLES_CSS__,'text/css; charset=utf-8'], '/logic.mjs':[__LOGIC_MJS__,'text/javascript; charset=utf-8'], '/app.mjs':[__APP_MJS__,'text/javascript; charset=utf-8']};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const businessDates=(start,end)=>{const out=[];for(let t=new Date(start+'T12:00:00Z'),last=new Date(end+'T12:00:00Z');t<=last&&out.length<370;t.setUTCDate(t.getUTCDate()+1)){if(t.getUTCDay()!==0&&t.getUTCDay()!==6)out.push(t.toISOString().slice(0,10));}return out;};
const ownerEmails=new Set(['rdaniglad@gmail.com','daniela@zenatech.com']);
const loginPage=(message='Sign in to continue')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · Team Leave</title><style>:root{font-family:Inter,system-ui,sans-serif;color:#252543;background:#f7f8fa}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(100%,440px);background:white;border:1px solid #e8e6f1;border-radius:20px;padding:40px;box-shadow:0 18px 55px #26214c12}.mark{display:inline-grid;place-items:center;width:44px;height:44px;border-radius:13px;background:#6554af;color:white;font-weight:800;font-size:24px}h1{font-size:30px;letter-spacing:-.8px;margin:24px 0 10px}p{color:#62697c;line-height:1.6;margin:0 0 26px}a.button{display:block;text-align:center;background:#6554af;color:#fff;text-decoration:none;font-weight:700;border-radius:10px;padding:15px}a.button:focus-visible{outline:3px solid #a995f5;outline-offset:3px}.small{font-size:14px;margin:22px 0 0}</style></head><body><main class="card"><span class="mark" aria-hidden="true">✳</span><h1>Team Leave</h1><p>${message}</p><a class="button" href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a><p class="small">Access is limited to invited team members. Ask your manager if you need access.</p></main></body></html>`;
async function context(request,env){const id=request.headers.get('oai-authenticated-user-id'),email=request.headers.get('oai-authenticated-user-email')?.toLowerCase().trim();if(!id||!email)return {error:json({error:'Sign in to your private Site to continue.'},401)};if(!env.DB)return {error:json({error:'The team database is unavailable.'},503)};let person=await env.DB.prepare('SELECT * FROM people WHERE email = ?').bind(email).first();if(!person&&ownerEmails.has(email)){await env.DB.prepare('INSERT OR IGNORE INTO people (id,email,name,allowance,used,role) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),email,'Daniela Omena',25,0,'manager').run();person=await env.DB.prepare('SELECT * FROM people WHERE email = ?').bind(email).first();}if(!person)return {error:json({error:'Your account has not been added to this team. Ask the manager to add your email address.'},403)};return {person};}
async function state(env,person){const people=(await env.DB.prepare('SELECT id,email,name,allowance,used,role FROM people ORDER BY name').all()).results;const requests=(await env.DB.prepare('SELECT id,person,start,end,type,status,note,decision_note AS decisionNote,submitted,decided FROM requests ORDER BY submitted DESC').all()).results.filter(r=>person.role==='manager'||r.person===person.id||r.status==='approved').map(r=>person.role==='manager'||r.person===person.id?r:{...r,note:'',decisionNote:''});return {people,requests,me:person.id,role:person.role,minimumCoverage:Math.max(1,people.length-2)};}
async function api(request,env,path){const ctx=await context(request,env);if(ctx.error)return ctx.error;const {person}=ctx,manager=person.role==='manager';if(path==='/api/state'&&request.method==='GET')return json(await state(env,person));
let body;try{body=await request.json();if(!body||typeof body!=='object')throw Error();}catch{return json({error:'Enter valid request details.'},400)}
if(path==='/api/people'&&request.method==='POST'){if(!manager)return json({error:'Manager access required.'},403);const email=String(body.email||'').toLowerCase().trim(),name=String(body.name||'').trim(),allowance=Number(body.allowance);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||name.length<2||name.length>100||!Number.isInteger(allowance)||allowance<0||allowance>100)return json({error:'Enter a name, valid email and annual allowance from 0 to 100.'},400);try{await env.DB.prepare('INSERT INTO people (id,email,name,allowance,used,role) VALUES (?,?,?,?,0,?)').bind(crypto.randomUUID(),email,name,allowance,'employee').run();}catch{return json({error:'This email is already on the team.'},409)}return json(await state(env,person),201)}
const userMatch=path.match(/^\/api\/people\/([^/]+)$/);
if(userMatch&&request.method==='POST'){
  if(!manager)return json({error:'Manager access required.'},403);
  const target=await env.DB.prepare('SELECT * FROM people WHERE id=?').bind(userMatch[1]).first();
  if(!target)return json({error:'User not found.'},404);
  const name=String(body.name||'').trim(),allowance=Number(body.allowance),used=Number(body.used),role=String(body.role||'');
  if(name.length<2||name.length>100||![allowance,used].every(n=>Number.isInteger(n)&&n>=0&&n<=100)||used>allowance||!['employee','manager'].includes(role))return json({error:'Enter a name, valid balances and a role.'},400);
  if((target.id===person.id||ownerEmails.has(target.email))&&role!=='manager')return json({error:'The site owner cannot be changed to an employee.'},403);
  await env.DB.prepare('UPDATE people SET name=?,allowance=?,used=?,role=? WHERE id=?').bind(name,allowance,used,role,target.id).run();
  return json(await state(env,person));
}
if(path==='/api/requests'&&request.method==='POST'){const owner=manager&&body.person?String(body.person):person.id;const target=await env.DB.prepare('SELECT * FROM people WHERE id=?').bind(owner).first();if(!target)return json({error:'Employee not found.'},400);const start=String(body.start||''),end=String(body.end||''),note=String(body.note||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||start<today()||end<start||start.slice(0,4)!==end.slice(0,4)||start.slice(0,4)!==today().slice(0,4)||note.length>500)return json({error:'Choose valid dates in the current leave year and a note under 500 characters.'},400);const days=businessDates(start,end);if(!days.length||days.length>100)return json({error:'Select 1 to 100 weekdays.'},400);const existing=await env.DB.prepare("SELECT id FROM requests WHERE person=? AND status IN ('pending','approved') AND start<=? AND end>=? LIMIT 1").bind(owner,end,start).first();if(existing)return json({error:'An active request already overlaps these dates.'},409);const used=(await env.DB.prepare("SELECT start,end FROM requests WHERE person=? AND status='approved' AND substr(start,1,4)=?").bind(owner,today().slice(0,4)).all()).results.reduce((n,r)=>n+businessDates(r.start,r.end).length,0);if(days.length>target.allowance-target.used-used)return json({error:'This request exceeds the available balance.'},400);await env.DB.prepare('INSERT INTO requests (id,person,start,end,type,status,note,decision_note,submitted) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,start,end,'Vacation','pending',note,'',today()).run();return json(await state(env,person),201)}
const match=path.match(/^\/api\/requests\/([^/]+)(?:\/(decision|cancel))?$/);if(match){const item=await env.DB.prepare('SELECT * FROM requests WHERE id=?').bind(match[1]).first();if(!item)return json({error:'Request not found.'},404);if(item.status!=='pending')return json({error:'This request has already been decided.'},409);if(match[2]==='cancel'&&request.method==='POST'){if(item.person!==person.id)return json({error:'Only the requester can cancel.'},403);await env.DB.prepare("UPDATE requests SET status='cancelled',decided=? WHERE id=? AND status='pending'").bind(today(),item.id).run();return json(await state(env,person))}
if(match[2]==='decision'&&request.method==='POST'){if(!manager)return json({error:'Manager access required.'},403);if(item.person===person.id)return json({error:'A manager cannot approve their own request.'},403);const decision=String(body.decision||''),note=String(body.note||'').trim();if(!['approved','declined'].includes(decision)||note.length>500||decision==='declined'&&!note)return json({error:'Choose a decision and explain a decline.'},400);if(decision==='approved'){const target=await env.DB.prepare('SELECT * FROM people WHERE id=?').bind(item.person).first();const approved=(await env.DB.prepare("SELECT start,end FROM requests WHERE person=? AND status='approved' AND substr(start,1,4)=?").bind(item.person,item.start.slice(0,4)).all()).results.reduce((n,r)=>n+businessDates(r.start,r.end).length,0);if(businessDates(item.start,item.end).length>target.allowance-target.used-approved)return json({error:'The employee no longer has enough days.'},409);const conflicts=[];for(const day of businessDates(item.start,item.end)){const away=(await env.DB.prepare("SELECT DISTINCT person FROM requests WHERE status='approved' AND start<=? AND end>=?").bind(day,day).all()).results.map(x=>x.person);if(new Set([...away,item.person]).size>(await env.DB.prepare('SELECT COUNT(*) AS n FROM people').first()).n- Math.max(1,(await env.DB.prepare('SELECT COUNT(*) AS n FROM people').first()).n-2))conflicts.push(day)}if(conflicts.length&&!body.override)return json({error:'Confirm arranged coverage before approving this conflict.'},409)}await env.DB.prepare('UPDATE requests SET status=?,decision_note=?,decided=? WHERE id=? AND status=?').bind(decision,note,today(),item.id,'pending').run();return json(await state(env,person))}}
return json({error:'Not found.'},404)}
export default {async fetch(request,env){const path=new URL(request.url).pathname;try{if(path.startsWith('/api/'))return await api(request,env,path);const ctx=await context(request,env);if(path==='/login'){if(!ctx.error)return Response.redirect(new URL('/',request.url),302);return new Response(loginPage(ctx.error.status===403?'Your account is signed in but is not on this team. Ask your manager to add your email.':'Sign in to view your time off and team calendar.'),{status:ctx.error.status===403?403:200,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})}if(ctx.error)return new Response(loginPage(ctx.error.status===403?'Your account is signed in but is not on this team. Ask your manager to add your email.':'Sign in to view your time off and team calendar.'),{status:ctx.error.status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});const asset=assets[path];if(!asset)return new Response('Not found',{status:404});return new Response(asset[0],{headers:{'content-type':asset[1],'cache-control':'no-store'}})}catch(error){console.error('Team Leave error',error);return path.startsWith('/api/')?json({error:'Unable to complete that action right now. Please try again.'},503):new Response('The application is temporarily unavailable.',{status:503})}}};
